services:
  db:
    image: postgres:15-alpine
    container_name: postgres_db
    environment:
      POSTGRES_DB: vet_db
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - vet-network
    restart: always

  backend:
    image: aleksabuncic/vetapp-backend:latest
    container_name: vet_backend_app
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    depends_on:
      - db
    environment:
      SERVER_PORT: ${SERVER_PORT}
      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS}
      SPRING_DATASOURCE_URL: ${DB_URL}
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: ${JWT_EXPIRATION}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
    networks:
      - vet-network
    restart: always

  frontend:
    image: aleksabuncic/vetapp-frontend:latest
    container_name: vet_frontend_app
    ports:
      - "3000:80"
    networks:
      - vet-network
    restart: always

volumes:
  pgdata:

networks:
  vet-network:
    name: vet-network
    driver: bridge