name: Update Submodules

on:
  repository_dispatch:
    types: [ update-submodule ]
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Monorepo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.MONOREPO_PAT }}
          submodules: true
          fetch-depth: 0

      - name: Update Submodules to Latest Commit
        run: |
          git submodule update --remote --recursive

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.MONOREPO_PAT }}
          commit-message: "Auto-update: ${{ github.event.client_payload.repo }} (${{ github.event.client_payload.sha }})"
          title: "Update Submodules: ${{ github.event.client_payload.repo }}"
          body: "Automated update of submodules triggered by push to ${{ github.event.client_payload.repo }}."
          branch: "auto-update-${{ github.event.client_payload.repo || 'manual' }}"
          base: "main"
          delete-branch: true

      - name: Enable Pull Request Automerge
        if: steps.cpr.outputs.pull-request-operation == 'created'
        run: gh pr merge --auto --merge "${{ steps.cpr.outputs.pull-request-number }}"
        env:
          GH_TOKEN: ${{ secrets.MONOREPO_PAT }}