name: Update Submodules

on:
  repository_dispatch:
    types: [ update-submodule ]
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Monorepo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.MONOREPO_PAT }}
          submodules: true
          fetch-depth: 0

      - name: Update Submodules to Latest Commit
        run: |
          git submodule update --remote --recursive

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          SOURCE_REPO="${{ github.event.client_payload.repo || 'Manual Update' }}"
          SHORT_SHA=$(echo "${{ github.event.client_payload.sha || 'unknown' }}" | cut -c1-7)
          
          git add .
          if git diff-index --quiet HEAD; then
            echo "No changes to commit"
          else
            git commit -m "Auto-update: $SOURCE_REPO ($SHORT_SHA)"
            git push
          fi